definitions:
  environment:
    event_scanner_signing: &event_scanner_signing
      XCODE_SCHEME: 'ShanyaiEvents'
      XCODE_PROJECT_PATH: 'ios/*.xcodeproj'
      XCODE_WORKSPACE_PATH: 'ios/*.xcworkspace'
      XCODE_PROJECT_PATTERN: 'ios/*.xcodeproj'
      BUNDLE_ID: 'co.event.scanner'
      BUNDLE_ID_IDENTIFIER: 'co.event.scanner'
      PLAY_STORE_API: Encrypted(Z0FBQUFBQmk0eEpVZ1ZuaWNVMUxjR1lobGpCM2VhN21BYTZzZXcwWU1NU1FraWhjNkliT2tfZDVDQlU4Yjl4LUdqU0E4cEgtenBfbXZWd0F4YWxOQTBHaHY2NGlXcFdTWV92SEZVU0R6ZjFJVVpvbmtPVVVpQXpXQWlTUm5vVEdRWHkwcGpnZTJfbGRJQ01vWW5TVVVYZndiN2IzblQ4Vzg3VUVEYjR1QWNSa29kUjJsVHZNaXlOXzBlbzd1dDB6aDBmTWdIM3Z5bWRfdF9iZzhBUGR5U0J0cVFVemJRdE1heV9UQXd6ejNYdTk2dmlKQ29KS3FxVnY5UU5yYW14MnV6a0x0emR0LVpQZS1jamdLRFdsUTBGcks1TllnRl9sM2lDMUZOdnVPTlRqa3ZxQUw0T2ZfZnFNZjQ0TjBGRGlDOVhHNThoMjFjbVJIc0pLMlBGS1lJdXF2YnUyS00xZkJZcWVZUzR4Q0tYYjUtRVRTQVVnM08yUWMtQUFSRUl5OWE0eHFJdTdWOTQyOXVOcFNQQlNBQzcxamFrWDROdXVXRFFHZXpxTXZCZEZlOHYxcmJnYWo1aVZpZW9mRDEzSEozZHA2dTVHeUprMmJGd3YySkZjTUxuWE5tLWo1T1g4U1ByWmo4Mmc5bjMtajQxb3JzWHB3TjVxeGFfZk5ZWEhMOG9XbGdXa0RBU1lRcUZUOWlFNWJycjJJQnJjdWYwT2ZZQkRCYlBFRUk3ZUFUYk1zQUZFTmo5Z2V5QzQwODBZUzBnXzhzZUtpME14YnZWdkdockdXY1dxLUhyUVphS0hobExHSTRQb012Uko1NGI2eThnZnlKQmloeEFiM1V0X042a1lnaDNuY2V5cHdiWlRUV0J4eTFENU9Yd0pvc2kwUkJmb2JuNjdsT2VFRkt0RG1PdWtZLU0zSEdmQTZwcDM3S09GbGFQVkdUbkdKdWk0Q2VpenFNNmlYTGdWYUtEQ3ZIVS10MUFzWUtTZmN0czh1ZWZhMDhXTnpXai1FUEkxQXNLNUtmNkthMWhnYXZ3QmZCaE5zX3RCUERFVnRfU3lRaTctOGwyQjd2ZHhvLXR4UU9NNHAyZHRNUzltTFk4b2dUOXoyWFplaUxycGpRV1NGNFN0ekFJU0RjM2Z2S0lQQnBTakpXb0RNSEdsRHhPNXN6LWUwU2tVbmE4eTk4MnZGOGMxTGNIUTV0VUVXdVk4WFpCZ3BxOS1qTjlqWV9PYjJiek5wY2JLLVBwYUVJYnVhSFdhZmowNHo4bkJsTERyeng1TmcyekItN0dfSGxXTVdEeElBY0l5eWo4WWVlclJnUlNXYVBwWVVyd2ZwYllNSk93SU9scTdfdThERU1zSkljSUh3OXVLMEFZYWxtNE9qaVBudlNOM0V1bnNVSmV3OW5WRldEWWhUbUpHTUdTUEFnQUdGVG9xRFhJd0dnTWxkUXZid2tpbTNaQWFXdlFJVzZpOFhYdmJPcnVBYUJ0WHh6SnZiNmVfc2xEYjdOTkthSFNIdldpcDdIbG14b250MmRic3R2Nk8waFgxSjgweWRGWXJocVBpSTFXS0F2amUzRjdnamt2MHpnOVh5ZHlrNU4xeWRBcFFPSFYwOXBzeURPRkdYN0xXSHZVRzdSX21BZ01HVUt6S0pRMzVOZjBZNDJzWUx6MmVRT1hDejBkc0dNV2g3b0FRTlNiM29IWmRZTTRxQWUyay05d1B2UUdrLWJyMU9JX3hHR2JhLXV6V19KWjdGWGZlbG9IN0QxV090RzVyNnUwR2JMc3RkNWdaTzRSem5EcHlHajAxbHNaaGNsZDdpZ0RYR2NSYXBZTFFHcWs5MXZyY0dORDlvdTAyaXV0Q09LQjY3dnNBYVkxeVZBOFJ5RjBxQVZDd3J0emFLYmJJb3FwQTBhWEdwWFV0UGtwV2t0endpa3ExMndtOGJlNTN4ekhEeThmVzN1TVdpVEh3ODZsWHpFYmlJN0RfQWJRT0ZWMTFEaTdfUDVRekJmYjc3RWhRdXRxelhfRW9JWlRNMlowVzVpUXlQSTdsXzNPZjhrYmQxaGFTM2ZKZnZ3NTBTalhoaHRtQ0VVdDlla3BXeVNacDhYTTU1RE5WbXRacVBpVFJDRkEzX0lTQllma19lMDY0SG1pRGhzXzJIRXV1NzM2MTIzVkdYaUEtSWYtdlhYUVV2T3NfZ2hQSFVjTExMMkRNbm45X3kycFZLdENiLWxTN0RwQ0k3ZFZISGZBQTVQUndfMEtuMlEzeGwtR0lGQ1VOVjZxTm9DWVRySVNZZWVueWpGbUZCR1dkLU9DWWhHRHpna3JiVFU4NjRRWVB2M0lLaUg0cmxoTkg2Ymd2NzNjWTZrVTNPSVo2eHVqY011X3VRRGh6emYzaFlBVVE1UUZVZEJGS0NQRnhWQUl3b2ZhNGQ1ODNOSTZxTXF0RjFxRnBqY0hvcHB1Q28zOFJsNEJwbWNWc01DMklHZGN1T3BTb1JSUVM3RnFtckp3VlJra1A0aXdSMW5aS2tpV1l5c09UcVZpMmdOdHdOeHVCT21nQjduaHh6QThHVk9ad25rVEhLcGd4bmt3NEotWVJzeEJZSDFvZ3NGbVVRUVlUYk1BaUI3dGphcHFUZDlVN1NnSUQzVHlsVWd3QXJkSW9HRG1qeXhkSlZabWZYVDV2TTg5a2NoZjlNaWdwUGtGbFZkRzdyTXNuTWZBQTFhd0Vja0F2akliVUpsZnJfZ2puT2hpcFN2RV9BTGJMS2ZYcXJ3UVFvLTNQNUMxT2RNaUF3SEowQjEtXzJaMWpiaTlWNTJleUlNOWozMnRPeHFBaWVJak1TMHRPNTEtd3E2MkdYck9ORTV4YjdQMFhOcHlYQzhFbFo5VFpES1ZqdzZDVlFwNjlvZFB1WlhXdE4tWkJSM3B0aXRmUHJRZXh3bWhqQWw5emFraFk2SVoydl9EV0NIU01oR0x1aTVHT0xlVG9EWnp1cGJ2dTV5c0dEUzkzRDloZUpOY1lUT1NuQUhfaGpfck9aSnQ2QmFhdUFEb0pTU1FZT0pxUkRhaHBwRG0tSklRYVl4Z2t4bVBRMmozTWFCTW93a056Wm9USzdzLXd6emtmNFNOM1dnUkVEUHM2LWpsWk5NTlhkSnVxYnIzMGpTdTRtR05UVFVuZVJPLVBPaGZWd0wwcHllOTlXdzh1TVBPV2hKQnhGUU9IcUV3NGlTdkVGdGpiUnhUclJfLVhpa3BQeG1aUlhpYlMzTEptRWlSVmozYnoyRHBPM2xtaUlDaUJJNkEwREZtM2g1eGFlWHNzLXljQUpMRXNEMjEyQkx4MUR1dHp6VWN0U2o5RGdqTWZqLUlCRUc0enY1MFBtbTNZTWpRWTdNRHY2Rzk1TW51TGE2Sk5jTmJlYk5WN1JFVlIwc01LMkxsTjF0b3pxYUgxWDNoU3djLUVjMUJabXpZUWQ5WjFNOUJHTnRqRFpSTGNUUUgyV2RCZzRxY1pLQU83R1ZzYTR3Q3ljYk9xYS1uUGg5b0h1cDVheE9XNjlTTXFtTW56Y3U1cFUzYmQ3SWFoOV9BdWRhOFJhOTRrWll0Sm5nY1VpY2tnN0s4VFplRzQ3UlRmX2x2SVBGcUxwWVJjN2NHSW9LblE0c3RVQ2RoYTNSUHR4ZkxyM2dQQUtXVlJFY3dTTnVaenFjQ3h6MUQwVXpXbkk2bmNNMG9EdksyQjhYd1RrVElFeUp2YkVWSi02MTZDZzV5dGpZTmJvTWdKcWtmcmFQRk1GSDBSeS1FOXc3UW9PZmZuRjZSMndaZXNrbGxDc1dVemFyT09ha1pnaXlmSUhHbTYzSzkzc25ERFNFR1lGVnUtOVQ2VThaOHRVTm91SldmcmlXTWFxMng1TG5oY2tzaGNsUnl2OUFhTm1LTTFsZXl3ekNnNDNzVnFySlljMU5XNVY4YVFZMWFpTXlld1VJb3Vtdk5UQ2tsQWJqV2xoUjFpVmhGbTdFdnJKZDZsYjdBZ21RNWNTQ1h2NVB1TTV4ZEFueDV5bGlqZHdOcnFwbTZTdlJ2TzV1Rnp5Smg1R2Y5cHA2UlRCaFQ2OFVMbkFhbjE3ME9PU2VtOFJYeUY5QnhPMl9BdkxZUDhvT3ZlMFFTU1JKOVFCQVJ3SlZCemE2b0dqcHBfcU93dDZaVWFiRndnQjlPR0RsZGZiaXI0RUZ3UTRIME5mRFV2cEZqdm8zZE0zRXR6X1VOSV9tOS10bzV4cGQyM1poRGI3Z2c0OE0wMGtILU9wYWJ4NThsd0U5aWg0cXZWX2p5cGlYd2tLc1Q5RTFfM2tQUTN3YXRuNXI2TDNZSnd1MWJTS3o4ZDAxS3FneXdFRUIyLVdKYU5wMkMzc25JR1ZQUjY2V05IbFlQTWZjX29RdEl3UFNva1ZGSnRxVlFsWmxQZzBPc2hWUTlHMGFDYVh5Vlh5MTh1d3U4UmZHb0dXQ1BURnBLZE81WWw1ZjFEQ1k4cE9ya3ozN002OUxiOUR2SS1feF9EVy0xUjNmLWtUb0xLN0ZrTjM5cE5pVm15TWJCN1dKZWxvcXo3ZmFSdDQtMHhzVkQyMXhpSVNtVVAwTDBPcFhPaHViM0t3c0FhbUhxczdLZV9DcHJfdnFyMmY0ellsTGJVT1hZYmpNSVp4cVVudld3Z05RNXplekFVSjZjbzFVV0N6aS1RbU1KbXFxNjNQdlRueVpoUnNYX1pXYXY5VnRWeEQwdHE4S05QcGdvQjdOTWpjRXZyZkJJWDZSeW0wdmFPS09YVEdpZHllQ1pKNGhNeVRYcmpDZ0JEd2wtUklWYTd2RXhSZS1IRWVpNDFSV2xzT1Z0WGtBaHpCcVFhaUd6eGJSazI3aklWMHd1LW5BQXU3bFg2X0tWOHk4UVdmb3lzUFNKVkJIbmhYTjNHUDI5YU5kRVBYal9LdkJRTmZtdjZNVmo3amtoMTE0UnRJbDd5R2VlWlVEZzV0bDZTWEU5cjhLTVVEYXhBZVhjZmY0Z1JJNVJJeVd3YjA0ZDRaYlZhXzY2dVV2ZEpEajhISW84aEtxRlBJNTJNN0EybUZpYWlXRk5reS03TmktSHVpMm42RzFSLXdCNHZPdkdEWU9Sa2NMQk4yS0h3eU4wQXBzTWVyTDA0NHNWdk5OYU9aSVdmOUYxMU9nd082Snl1cXYxUE0tX1VjQjMzZ1JNMkstRXdhRTlGYS1GdU9ZSW1yUFlmMWcwdk9qRllYMmNOQkJuRHVrbUppRVZZNjRZQy14X0JsNnFnNjVDMGRJcm02SmdkcFlaRnpfbUtocl81alpMM3pLRjFVQzlJRlhDNVB4clBVVFVja0wxQk1rNWJCVi1SSU9lcl8ycV85NVdiaTc2ZnR4X1RzeVM0QThYeFN2c3U1SWxfdEdwTHhWUF8wVDFvTGdVWkJEdDJVS2ZGWHlwMHZINTlzZWIxSGpMdGlxdWpsT3lMTXVDZVpWTTMzWGdxU0ZjLTlZUDMzS195TGlWb09TOG9hUHdoYTQ1ZnJVb3FhRDN4cTBTSS1BQjJRUmJlbktEZ0RBcjVua0N4RmhKOHBmN3FPZHhxZjNhc1AzNkUzbDI1S1FlTUdFRG5GUm0zMTNoc2d3eTYtT2pwREJIMTgxWndxSF9BaWdsWDhOZGVtUGZ6QU00Y1N1MVlVQTlqc3NRcE1Oc3R1TGNJSXBrWjBPUGNfRFFZNjJQaVJYRjdFdTZ0OGI2M2JfNlAxdVdCNG5VTms4M2pkUU8yMFQyUmRaS2pJUzYtcmlUcnhUeHhPdi1FVUE9PQ==)
      VERSION_NUMBER: 1.0
      BUILD_NUMBER_BUMP: 1000
      APP_GALLERY_CLIENT_ID: 100
      APP_GALLERY_CLIENT_SECRET: '100'
  scripts:
    - &export_env_variables
      name: Export Environment Variables
      script: cd scripts; ./codemagic-env-variables.sh
    - &install_modules
      name: Install nodemodules
      script: yarn install
    - &ssh_key
      name: SSH KEY
      script: echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "android/local.properties"
    - &build_android
      name: Build Android
      script: |
        echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH   # Not required if using team code signing identities
        cd android && ./gradlew bundleRelease
    - &install_pods
      name: Install pods
      script: |
        cd ios; pod repo update; pod install
    - &ios_keychain
      name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      script: keychain initialize
    - &ios_signing_files
      name: Fetch signing files
      script: |
        app-store-connect fetch-signing-files $BUNDLE_ID \
        --type IOS_APP_STORE \
        --create
    - &ios_signing_certs
      name: Set up signing certificate
      script: keychain add-certificates
    - &ios_signing_setup
      name: Set up code signing settings on Xcode project
      script: xcode-project use-profiles
    - &ios_increment_build
      name: increment build number
      script: cd ios; agvtool new-version -all "$VERSION_NUMBER".$(($BUILD_NUMBER +1)); agvtool new-marketing-version "$VERSION_NUMBER".$(($BUILD_NUMBER +1));
    - &replace_text
      name: Target 12.4
      script: |
        sed -i -e "s/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 13.2.1/g" ios/Pods/Pods.xcodeproj/project.pbxproj
    - &ios_build
      name: Build ipa
      script: |
        cd ios; xcode-project build-ipa --workspace "eventScanner.xcworkspace" --scheme $XCODE_SCHEME
    - &clean_up_brands_not_required_for_given_flavor
      name: Clean Up Brands not required for the given Flavor
      script: cd $FCI_BUILD_DIR/tools/; ./codemagic-delete-unused-assets.sh ${XCODE_SCHEME}
  artifacts:
    - &apk android/app/build/outputs/apk/release/*.apk
    - &aab android/app/build/outputs/bundle/release/*.aab
    - &ipa ios/build/ios/ipa/*.ipa
    - &dsym $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
  publishing:
    slack: &slack
      channel: '#app-builds'
      notify_on_build_start: true
      notify:
        success: true
        failure: true
workflows:
  event_scan_app:
    name: EventScannerApp
    instance_type: mac_mini_m1
    environment:
      groups:
        - shanyai
      node: 19.0.0
      vars: *event_scanner_signing
    scripts:
      - *ios_keychain
      - *ios_signing_files
      - *install_modules
      - *ssh_key
      - *build_android
      - *install_pods
      - *ios_signing_certs
      - *ios_signing_setup
      - *ios_increment_build
      - *ios_build
    artifacts:
      - *apk
      - *aab
      - *ipa
      - *dsym
    publishing:
      google_play: # For Android app
        credentials: $PLAY_STORE_API
        track: internal
      app_store_connect: # For iOS app
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true # Name of the track: internal, alpha, beta, production, internal app sharing
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/Library/Caches/CocoaPods
